name: Increment version of updated languages

on:
  push:
    branches: [ matrix, language-test ]
    paths:
      - '**resource.language.**strings.po'
      - '**resource.language.**langinfo.xml'

jobs:
  default:
    runs-on: ubuntu-latest
    name: Increment version of updated languages

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Get changed files
        uses: trilom/file-changes-action@v1.2.4

      - name: Increment version of updated languages
        run: |
          python3 increment_version.py $HOME/files.json

      - name: Create PR for incremented versions
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: Language add-on versions incremented
          title: Language add-on versions incremented
          body: Language add-on versions incrementing triggered by ${{ github.sha }}
          branch: inc-ver
          delete-branch: true
          reviewers: gade01